### ISSUE TITLE
Unable to compile on latest Ubuntu LTS 18.04

### ISSUE THREAD

**Issue by J-A-M-E-5** [nvmedirect/nvmedirect#19]
Hi I have tested latest version of code in this repo as well as code I found at https://github.com/nvmedirect/nvmedirect_v2 uploaded just a few hours ago. Both exhibit the same problem in the make fails for the MODULES.

```
modules/nvmed-core.c:39:26: error: passing argument 1 of ‘nvmed_submit_cmd’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   ret = nvmed_submit_cmd(dev, cmd, result);
```
Using latest Ubuntu LTS, gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3) brand new install with just build-essential installed.

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"
```

```
$ uname -a
Linux bionic 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

If I install gcc 4.8 and set CC=/usr/bin/gcc-4.8 in the Makefile I get these errors:-
```
gcc-4.8: error: unrecognized command line option ‘-mskip-rax-setup’
gcc-4.8: error: unrecognized command line option ‘-fstack-protector-strong’
```

Full logs (make) and (make -d) are attached. Thanks.

[make.log](https://github.com/nvmedirect/nvmedirect/files/1973855/make.log)
[make-d.log](https://github.com/nvmedirect/nvmedirect/files/1973856/make-d.log)

**Comment by hyeongjunkim** [comment]
Hello @J-A-M-E-5 

I will upload it again with the manual, including operating environment.

Thanks.
